CREATE TYPE STATUS AS ENUM
('ATIVO', 'DESLIGADO', 'FERIAS');

CREATE TABLE FUNCIONARIO
(
    --ENUM!
    STATUS STATUS NOT NULL,  -- 'ATIVO', 'DESLIGADO', 'FERIAS'
    CPF VARCHAR(12) NOT NULL,
    RG VARCHAR(15) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    NOME_PAI VARCHAR(100),
    NOME_MAE VARCHAR(100),
    ADMISSAO DATE NOT NULL,
    DESLIGAMENTO DATE,
    FACEBOOK VARCHAR(100),
    SKYPE VARCHAR(100),
    LINKEDIN VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE NUMERIC(11) NOT NULL,
    TELEFONE_ALT NUMERIC(11),
    EMAIL_ALT VARCHAR(100),
    RA NUMERIC(7) NOT NULL, 
    COEFICIENTE VARCHAR(6) NOT NULL,
    PERIODO NUMERIC(1) NOT NULL,
    END_RUA VARCHAR(80) NOT NULL,
    END_BAIRRO VARCHAR(30) NOT NULL,
    END_NUMERO VARCHAR(5) NOT NULL,
    END_COMPLEMENTO VARCHAR(30),
    END_CEP VARCHAR(9) NOT NULL,
    ID_CIDADE INTEGER NOT NULL,
    ID_VINCULO INTEGER NOT NULL,
    ID_CARGO INTEGER NOT NULL,
    ID_SETOR INTEGER NOT NULL,
    ID_ESTADO_CIVIL INTEGER NOT NULL,
    CONSTRAINT PK_FUNCIONARIO
    PRIMARY KEY(CPF),
    CONSTRAINT UK_FUNCIONARIO_RG
    UNIQUE (RG),
    CONSTRAINT UK_FUNCIONARIO_EMAIL
    UNIQUE (EMAIL),
    CONSTRAINT UK_FUNCIONARIO_RA
    UNIQUE(RA)
);
CREATE TABLE CIDADE
(
    ID_CIDADE INTEGER NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    CONSTRAINT PK_CIDADE
    PRIMARY KEY(ID_CIDADE)
);
CREATE TABLE ESTADO
(   
    UF VARCHAR(2) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ESTADO
    PRIMARY KEY(UF)
);
CREATE TABLE VINCULO
(
    ID_VINCULO INTEGER NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_VINCULO
    PRIMARY KEY (ID_VINCULO),
    CONSTRAINT UK_VINCULO_NOME
    UNIQUE (NOME)
);
CREATE TABLE CARGO
(
    ID_CARGO INTEGER NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_CARGO
    PRIMARY KEY(ID_CARGO),
    CONSTRAINT UK_CARGO_NOME
    UNIQUE (NOME)
);
CREATE TABLE SETOR
(
    ID_SETOR INTEGER NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_SETOR
    PRIMARY KEY(ID_SETOR),
    CONSTRAINT UK_SETOR_NOME
    UNIQUE (NOME)
);
CREATE TABLE PONTO_FUNCIONARIO
(
    DATA DATE NOT NULL,
    --ENTRADA TIME,
    --STATUS VARCHAR(1) NOT NULL,  -- 'A' ativo, 'D' desligado, 'F' ferias
    ENTRADA TIME NOT NULL,
    SAIDA TIME,
    CPF VARCHAR(12) NOT NULL,
    CONSTRAINT PK_PONTO_FUNCIONARIO
    PRIMARY KEY(DATA, CPF)
);
CREATE TABLE LOG_ALTERACAO
(
    DATA_HORA TIMESTAMP NOT NULL,
    TABELA VARCHAR(30) NOT NULL,
    CAMPO VARCHAR(30) NOT NULL,
    REGISTRO_ANTIGO VARCHAR(100) NOT NULL,
    CPF_ALTERADO VARCHAR(12) NOT NULL,
    CPF_RESPONSAVEL VARCHAR(12) NOT NULL,
    CONSTRAINT PK_LOG_ALTERACAO
    PRIMARY KEY (DATA_HORA, TABELA, CAMPO, CPF_ALTERADO, CPF_RESPONSAVEL)
);
CREATE TABLE CONTA_BANCARIA
(
    CONTA INTEGER NOT NULL,
    AGENCIA INTEGER NOT NULL,
    ID_BANCO INTEGER NOT NULL,
    CPF VARCHAR(12) NOT NULL,
    CONSTRAINT PK_CONTA_BANCARIA
    PRIMARY KEY (CONTA, AGENCIA, CPF)
);
CREATE TABLE BANCO
(
    ID_BANCO INTEGER NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CONSTRAINT PK_BANCO
    PRIMARY KEY(ID_BANCO),
    CONSTRAINT UK_BANCO_NOME
    UNIQUE (NOME)
);
CREATE TABLE ESTADO_CIVIL
(
    ID_ESTADO_CIVIL INTEGER NOT NULL,
    NOME VARCHAR(15) NOT NULL,
    CONSTRAINT PK_ESTADO_CIVIL
    PRIMARY KEY(ID_ESTADO_CIVIL),
    CONSTRAINT UK_ESTADOCIVIL_NOME
    UNIQUE (NOME)
);
CREATE TABLE LOGIN
(
    CPF VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(80) NOT NULL,
    ULTIMO_ACESSO TIMESTAMP,
    CONSTRAINT PK_LOGIN
    PRIMARY KEY(CPF)
);

ALTER TABLE FUNCIONARIO
ADD
CONSTRAINT FK_FUNCIONARIO_IDCIDADE
FOREIGN KEY (ID_CIDADE)
REFERENCES CIDADE(ID_CIDADE);

ALTER TABLE FUNCIONARIO
ADD
CONSTRAINT FK_FUNCIONARIO_IDVINCULO
FOREIGN KEY (ID_VINCULO)
REFERENCES VINCULO(ID_VINCULO);

ALTER TABLE FUNCIONARIO
ADD
CONSTRAINT FK_FUNCIONARIO_IDCARGO
FOREIGN KEY (ID_CARGO)
REFERENCES CARGO(ID_CARGO);

ALTER TABLE FUNCIONARIO
ADD
CONSTRAINT FK_FUNCIONARIO_IDSETOR
FOREIGN KEY (ID_SETOR)
REFERENCES SETOR(ID_SETOR);

ALTER TABLE FUNCIONARIO
ADD
CONSTRAINT FK_FUNCIONARIO_IDESTADOCIVIL
FOREIGN KEY (ID_ESTADO_CIVIL)
REFERENCES ESTADO_CIVIL(ID_ESTADO_CIVIL);

ALTER TABLE CIDADE
ADD
CONSTRAINT FK_CIDADE_IDESTADO
FOREIGN KEY (UF)
REFERENCES ESTADO(UF);

ALTER TABLE PONTO_FUNCIONARIO
ADD
CONSTRAINT FK_PONTOFUNCIONARIO_CPF
FOREIGN KEY (CPF)
REFERENCES FUNCIONARIO(CPF);

ALTER TABLE LOG_ALTERACAO
ADD
CONSTRAINT FK_LOGALTERACAO_CPFALTERADO
FOREIGN KEY(CPF_ALTERADO)
REFERENCES FUNCIONARIO(CPF);

ALTER TABLE LOG_ALTERACAO
ADD
CONSTRAINT FK_LOGALTERACAO_CPFRESPONSAVEL
FOREIGN KEY (CPF_RESPONSAVEL)
REFERENCES FUNCIONARIO(CPF);

ALTER TABLE CONTA_BANCARIA
ADD
CONSTRAINT FK_CONTABANCARIA_IDBANCO
FOREIGN KEY(ID_BANCO)
REFERENCES BANCO(ID_BANCO);

ALTER TABLE CONTA_BANCARIA
ADD
CONSTRAINT FK_CONTABANCARIA_CPF
FOREIGN KEY(CPF)
REFERENCES FUNCIONARIO(CPF);

ALTER TABLE LOGIN
ADD
CONSTRAINT FK_LOGIN_CPF
FOREIGN KEY(CPF)
REFERENCES FUNCIONARIO(CPF);

ALTER TABLE LOGIN
ADD
CONSTRAINT FK_LOGIN_EMAIL
FOREIGN KEY(EMAIL)
REFERENCES FUNCIONARIO(EMAIL);  

CREATE INDEX IDX_PONTO_FUNCIONARIO_CPF
ON PONTO_FUNCIONARIO USING BTREE (CPF);

CREATE INDEX IDX_LOG_ALTERACAO_CPF_ALTERADO
ON LOG_ALTERACAO USING BTREE (CPF_ALTERADO);