----------------------------------------BUSCA----------------------------------------
-- QUERY QUE RETORNA TODOS OS CPF E TODOS OS NOMES DE USUÁRIOS BASEADO NA ENTRADA DE UMA PARTE DE UM NOME
-- ALTERAR $S_nome POR NOME DIGITADO NO CAMPO DE BUSCA
SELECT CPF, NOME
	FROM FUNCIONARIO
		WHERE NOME LIKE '%$S_nome%' --CUIDADO COM AS ASPAS E OS PORCENTOS, DEVEM SER MANTIDOS
-- FIM QUERY
----------------------------------------FIM------------------------------------------

----------------------------------------RECUPERAÇÃO DE SENHA-------------------------
-- QUERY QUE DÁ UPDATE EM SENHA JÁ EXISTENTE BASEADO EM EMAIL
-- ALTERAR $S_senha POR SENHA A SER INSERIDA
-- ALTERAR $S_email POR EMAIL CUJA SENHA ESTÁ SENDO ALTERADA
UPDATE LOGIN
	SET SENHA = '$S_senha' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
		WHERE EMAIL = '$S_email' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
-- FIM QUERY

-- QUERY QUE DÁ UMDATE EM SENHA JÁ EXISTENTE BASEADO EM CPF
-- ALTERAR $S_senha POR SENHA A SER INSERIDA
-- ALTERAR $S_cpf POR CPF CUJA SENHA ESTÁ SENDO ALTERADA
UPDATE LOGIN
	SET SENHA = '$S_senha' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
		WHERE CPF = '$S_cpf' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
-- FIM QUERY

-- QUERY QUE DÁ UMDATE EM SENHA JÁ EXISTENTE BASEADO EM EMAIL E CPF (MAIS SEGURO)
-- ALTERAR $S_senha POR SENHA A SER INSERIDA
-- ALTERAR $S_email POR EMAIL CUJA SENHA ESTÁ SENDO ALTERADA
-- ALTERAR $S_cpf POR CPF CUJA SENHA ESTÁ SENDO ALTERADA
UPDATE LOGIN
	SET SENHA = '$S_senha' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
		WHERE EMAIL = '$S_email' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
		AND   CPF = '$S_cpf' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
-- FIM QUERY
----------------------------------------FIM------------------------------------------

----------------------------------------ACESSO AO PERFIL-----------------------------
-- QUERY QUE SELECIONA TODOS OS DADOS CADASTRAIS DO FUNCIONARIO A PARTIR DE UM CPF
-- ALTERAR $S_cpf POR CPF DE QUEM OS DADOS SERÃO EXIBIDOS
SELECT F.CPF, F.RG, F.NOME, F.NASCIMENTO, F.SEXO, F.NOME_PAI, F.NOME_MAE,
	   F.ADMISSAO, F.FACEBOOK, F.SKYPE, F.LINKEDIN, F.EMAIL, F.TELEFONE,
	   F.TELEFONE_ALT, F.EMAIL_ALT, F.RA, F.COEFICIENTE, F.PERIODO,
	   F.END_RUA, F.END_BAIRRO, F.END_NUMERO, F.END_COMPLEMENTO,
	   F.END_CEP, CIDADE.NOME AS CIDADE, E.NOME AS ESTADO,
	   V.NOME AS VINCULO, C.NOME AS CARGO, S.NOME AS SETOR,
	   ES.NOME AS ESTADO_CIVIL
	FROM FUNCIONARIO F
		INNER JOIN CIDADE
			ON F.ID_CIDADE = CIDADE.ID_CIDADE
			INNER JOIN ESTADO E
				ON CIDADE.UF = E.UF
				INNER JOIN VINCULO V
					ON F.ID_VINCULO = V.ID_VINCULO
					INNER JOIN CARGO C
						ON F.ID_CARGO = C.ID_CARGO
							INNER JOIN SETOR S
								ON F.ID_SETOR = S.ID_SETOR
								INNER JOIN ESTADO_CIVIL ES
									ON F.ID_ESTADO_CIVIL = ES.ID_ESTADO_CIVIL
	WHERE CPF = '$S_cpf' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
-- FIM QUERY

-- QUERY QUE SELECIONA TODOS OS DADOS CADASTRAIS DO FUNCIONARIO A PARTIR DE UM RG
-- ALTERAR $S_rg POR RG DE QUEM OS DADOS SERÃO EXIBIDOS
SELECT F.CPF, F.RG, F.NOME, F.NASCIMENTO, F.SEXO, F.NOME_PAI, F.NOME_MAE,
	   F.ADMISSAO, F.FACEBOOK, F.SKYPE, F.LINKEDIN, F.EMAIL, F.TELEFONE,
	   F.TELEFONE_ALT, F.EMAIL_ALT, F.RA, F.COEFICIENTE, F.PERIODO,
	   F.END_RUA, F.END_BAIRRO, F.END_NUMERO, F.END_COMPLEMENTO,
	   F.END_CEP, CIDADE.NOME AS CIDADE, E.NOME AS ESTADO,
	   V.NOME AS VINCULO, C.NOME AS CARGO, S.NOME AS SETOR,
	   ES.NOME AS ESTADO_CIVIL
	FROM FUNCIONARIO F
		INNER JOIN CIDADE
			ON F.ID_CIDADE = CIDADE.ID_CIDADE
			INNER JOIN ESTADO E
				ON CIDADE.UF = E.UF
				INNER JOIN VINCULO V
					ON F.ID_VINCULO = V.ID_VINCULO
					INNER JOIN CARGO C
						ON F.ID_CARGO = C.ID_CARGO
							INNER JOIN SETOR S
								ON F.ID_SETOR = S.ID_SETOR
								INNER JOIN ESTADO_CIVIL ES
									ON F.ID_ESTADO_CIVIL = ES.ID_ESTADO_CIVIL
	WHERE RG = '$S_rg' --CUIDADO COM AS ASPAS, DEVEM SER MANTIDAS
-- FIM QUERY
----------------------------------------FIM------------------------------------------