INSERT INTO ESTADO (NOME, UF) VALUES('ACRE', 'AC');
INSERT INTO ESTADO (NOME, UF) VALUES('ALAGOAS', 'AL');
INSERT INTO ESTADO (NOME, UF) VALUES('AMAZONAS', 'AM');
INSERT INTO ESTADO (NOME, UF) VALUES('AMAPA', 'AP');
INSERT INTO ESTADO (NOME, UF) VALUES('BAHIA', 'BA');
INSERT INTO ESTADO (NOME, UF) VALUES('CEARA', 'CE');
INSERT INTO ESTADO (NOME, UF) VALUES('DISTRITO FEDERAL', 'DF');
INSERT INTO ESTADO (NOME, UF) VALUES('ESPIRITO SANTO', 'ES');
INSERT INTO ESTADO (NOME, UF) VALUES('GOIAS', 'GO');
INSERT INTO ESTADO (NOME, UF) VALUES('MARANHAO', 'MA');
INSERT INTO ESTADO (NOME, UF) VALUES('MINAS GERAIS', 'MG');
INSERT INTO ESTADO (NOME, UF) VALUES('MATO GROSSO DO SUL', 'MS');
INSERT INTO ESTADO (NOME, UF) VALUES('MATO GROSSO', 'MT');
INSERT INTO ESTADO (NOME, UF) VALUES('PARA', 'PA');
INSERT INTO ESTADO (NOME, UF) VALUES('PARAIBA', 'PB');
INSERT INTO ESTADO (NOME, UF) VALUES('PERNAMBUCO', 'PE');
INSERT INTO ESTADO (NOME, UF) VALUES('PIAUI', 'PI');
INSERT INTO ESTADO (NOME, UF) VALUES('PARANA', 'PR');
INSERT INTO ESTADO (NOME, UF) VALUES('RIO DE JANEIRO', 'RJ');
INSERT INTO ESTADO (NOME, UF) VALUES('RIO GRANDE DO NORTE', 'RN');
INSERT INTO ESTADO (NOME, UF) VALUES('RONDONIA', 'RO');
INSERT INTO ESTADO (NOME, UF) VALUES('RORAIMA', 'RR');
INSERT INTO ESTADO (NOME, UF) VALUES('RIO GRANDE DO SUL', 'RS');
INSERT INTO ESTADO (NOME, UF) VALUES('SANTA CATARINA', 'SC');
INSERT INTO ESTADO (NOME, UF) VALUES('SERGIPE', 'SE');
INSERT INTO ESTADO (NOME, UF) VALUES('SAO PAULO', 'SP');
INSERT INTO ESTADO (NOME, UF) VALUES('TOCANTINS', 'TO');

INSERT INTO CIDADE
VALUES
(1, 'DOIS VIZINHOS', 'PR'), (2, 'FRANCISCO BELTRAO', 'PR'), (3, 'PATO BRANCO', 'PR');

INSERT INTO VINCULO
VALUES 
(1, 'TRAINEE'), (2, 'EFETIVO'); 

INSERT INTO CARGO 
VALUES (1, 'FUNCIONARIO'), (2, 'GESTOR'), (3, 'DIRETOR');

INSERT INTO SETOR
VALUES (1, 'MARKETING'), (2, 'QUALIDADE'), (3, 'RH'),
(4, 'PROJETOS'), (5, 'ADMINISTRATIVO-FINANCEIRO'), (6, 'VICEPRESIDENCIA'), (7, 'PRESIDENCIA');

INSERT INTO ESTADO_CIVIL
VALUES
(1, 'SOLTEIRO(A)'), (2, 'CASADO(A)'), (3, 'DIVORCIADO(A)'),
(4, 'SEPARADO(A)'), (5, 'UNIAO ESTAVEL'), (6, 'VIUVO(A)');

INSERT INTO BANCO
VALUES
(1, 'BANCO DO BRASIL'), (2, 'CAIXA ECONOMICA FEDERAL'), (3, 'SANTANDER'),
(4, 'BRADESCO'), (5, 'ITAU'), (6, 'SICREDI'),
(7, 'SICOOB'), (8, 'NUBANK'), (9, 'CITIBANK'), (10, 'HSBC'), (11, 'CRESOL');